package no.uio.inf5040.obl1.tasteprofiler;

/**
 * TasteProfile/ProfilerHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from tasteprofile.idl Thursday, September 18, 2014
 * 1:26:03 PM CEST
 */

/*
 * The service interface with the methods that can be invoked remotely by
 * clients
 */
public final class ProfilerHolder implements org.omg.CORBA.portable.Streamable {
	public no.uio.inf5040.obl1.tasteprofiler.Profiler value = null;

	public ProfilerHolder() {
	}

	public ProfilerHolder(
			no.uio.inf5040.obl1.tasteprofiler.Profiler initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = no.uio.inf5040.obl1.tasteprofiler.ProfilerHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		no.uio.inf5040.obl1.tasteprofiler.ProfilerHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return no.uio.inf5040.obl1.tasteprofiler.ProfilerHelper.type();
	}

}
