package no.uio.inf5040.obl1.tasteprofiler;

/**
 * TasteProfile/Profiler.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from tasteprofile.idl Thursday, September 18, 2014
 * 1:26:03 PM CEST
 */

/*
 * The service interface with the methods that can be invoked remotely by
 * clients
 */
public interface Profiler extends ProfilerOperations, org.omg.CORBA.Object,
		org.omg.CORBA.portable.IDLEntity {
} // interface Profiler
