package no.uio.inf5040.obl1.tasteprofiler;

/**
 * TasteProfile/ProfilerOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from tasteprofile.idl Thursday, September 18, 2014
 * 1:26:03 PM CEST
 */

/*
 * The service interface with the methods that can be invoked remotely by
 * clients
 */
public interface ProfilerOperations {

	/* Returns how many times a given song was played by all the users */
	int getTimesPlayed(String song_id);

	/* Returns how many times a given song was played by a given user */
	int getTimesPlayedByUser(String user_id, String song_id);
} // interface ProfilerOperations
