package no.uio.inf5040.obl1.tasteprofile;

/**
 * no/uio/inf5040/obl1/tasteprofile/ProfilerHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from tasteprofile.idl Friday,
 * October 3, 2014 12:28:57 PM CEST
 */

/*
 * The service interface with the methods that can be invoked remotely by
 * clients
 */
public final class ProfilerHolder implements org.omg.CORBA.portable.Streamable {
	public no.uio.inf5040.obl1.tasteprofile.Profiler value = null;

	public ProfilerHolder() {
	}

	public ProfilerHolder(no.uio.inf5040.obl1.tasteprofile.Profiler initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = no.uio.inf5040.obl1.tasteprofile.ProfilerHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		no.uio.inf5040.obl1.tasteprofile.ProfilerHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return no.uio.inf5040.obl1.tasteprofile.ProfilerHelper.type();
	}

}
