package no.uio.inf5040.obl1.tasteprofile;

/**
 * no/uio/inf5040/obl1/tasteprofile/Profiler.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from tasteprofile.idl Thursday, September
 * 25, 2014 5:32:42 PM CEST
 */

/*
 * The service interface with the methods that can be invoked remotely by
 * clients
 */
public interface Profiler extends ProfilerOperations, org.omg.CORBA.Object,
		org.omg.CORBA.portable.IDLEntity {
} // interface Profiler
