package no.uio.inf5040.obl1.tasteprofile;

/**
 * no/uio/inf5040/obl1/tasteprofile/SongHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from tasteprofile.idl Friday,
 * October 3, 2014 12:28:57 PM CEST
 */

/* valuetype containing info about a song */
abstract public class SongHelper {
	private static String _id = "IDL:no.uio.inf5040.obl1.tasteprofile/Song:1.0";

	public static void insert(org.omg.CORBA.Any a,
			no.uio.inf5040.obl1.tasteprofile.Song that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static no.uio.inf5040.obl1.tasteprofile.Song extract(
			org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	private static boolean __active = false;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			synchronized (org.omg.CORBA.TypeCode.class) {
				if (__typeCode == null) {
					if (__active) {
						return org.omg.CORBA.ORB.init()
								.create_recursive_tc(_id);
					}
					__active = true;
					org.omg.CORBA.ValueMember[] _members0 = new org.omg.CORBA.ValueMember[2];
					org.omg.CORBA.TypeCode _tcOf_members0 = null;
					// ValueMember instance for id
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(
							0);
					_members0[0] = new org.omg.CORBA.ValueMember("id", "", _id,
							"", _tcOf_members0, null,
							org.omg.CORBA.PUBLIC_MEMBER.value);
					// ValueMember instance for play_count
					_tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(
							org.omg.CORBA.TCKind.tk_long);
					_members0[1] = new org.omg.CORBA.ValueMember("play_count",
							"", _id, "", _tcOf_members0, null,
							org.omg.CORBA.PUBLIC_MEMBER.value);
					__typeCode = org.omg.CORBA.ORB.init().create_value_tc(_id,
							"Song", org.omg.CORBA.VM_NONE.value, null,
							_members0);
					__active = false;
				}
			}
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static no.uio.inf5040.obl1.tasteprofile.Song read(
			org.omg.CORBA.portable.InputStream istream) {
		return (no.uio.inf5040.obl1.tasteprofile.Song) ((org.omg.CORBA_2_3.portable.InputStream) istream)
				.read_value(id());
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			no.uio.inf5040.obl1.tasteprofile.Song value) {
		((org.omg.CORBA_2_3.portable.OutputStream) ostream).write_value(value,
				id());
	}

}
