package no.uio.inf5040.obl1.tasteprofile;

/**
 * no/uio/inf5040/obl1/tasteprofile/SongHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from tasteprofile.idl Friday,
 * October 3, 2014 12:28:57 PM CEST
 */

/* valuetype containing info about a song */
public final class SongHolder implements org.omg.CORBA.portable.Streamable {
	public no.uio.inf5040.obl1.tasteprofile.Song value = null;

	public SongHolder() {
	}

	public SongHolder(no.uio.inf5040.obl1.tasteprofile.Song initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = no.uio.inf5040.obl1.tasteprofile.SongHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		no.uio.inf5040.obl1.tasteprofile.SongHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return no.uio.inf5040.obl1.tasteprofile.SongHelper.type();
	}

}
