package no.uio.inf5040.obl1.tasteprofile;

import no.uio.inf5040.obl1.server.UserImpl;

/**
 * no/uio/inf5040/obl1/tasteprofile/UserDefaultFactory.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from tasteprofile.idl Friday,
 * October 3, 2014 12:28:57 PM CEST
 */

/* valuetype containing info about a user */
public class UserDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

	public java.io.Serializable read_value(
			org.omg.CORBA_2_3.portable.InputStream is) {
		return is.read_value(new UserImpl());
	}
}
