package no.uio.inf5040.obl1.tasteprofile;

/**
 * no/uio/inf5040/obl1/tasteprofile/User.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from tasteprofile.idl Friday, October 3,
 * 2014 12:28:57 PM CEST
 */

/* valuetype containing info about a user */
public abstract class User implements org.omg.CORBA.portable.StreamableValue {
	public String id = null;
	public no.uio.inf5040.obl1.tasteprofile.Song songs[] = null;

	private static String[] _truncatable_ids = { no.uio.inf5040.obl1.tasteprofile.UserHelper
			.id() };

	public String[] _truncatable_ids() {
		return _truncatable_ids;
	}

	public void _read(org.omg.CORBA.portable.InputStream istream) {
		this.id = istream.read_string();
		int _len0 = istream.read_long();
		this.songs = new no.uio.inf5040.obl1.tasteprofile.Song[_len0];
		for (int _o1 = 0; _o1 < this.songs.length; ++_o1)
			this.songs[_o1] = no.uio.inf5040.obl1.tasteprofile.SongHelper
					.read(istream);
	}

	public void _write(org.omg.CORBA.portable.OutputStream ostream) {
		ostream.write_string(this.id);
		ostream.write_long(this.songs.length);
		for (int _i0 = 0; _i0 < this.songs.length; ++_i0)
			no.uio.inf5040.obl1.tasteprofile.SongHelper.write(ostream,
					this.songs[_i0]);
	}

	public org.omg.CORBA.TypeCode _type() {
		return no.uio.inf5040.obl1.tasteprofile.UserHelper.type();
	}
} // class User
